### ISSUE TITLE
Not working update user with 'unsubscribed_from_emails'

### ISSUE THREAD

**Issue by lucasvmiguel** [tinycreative/react-native-intercom#195]
I'm trying to change the `unsubscribed_from_emails` to false, but it's not working on this library. However, when I try the same thing on the Intercom REST API it works.

snippet curl
```bash
curl https://api.intercom.io/users \
-X POST \
-H 'Authorization:Bearer <ACCESS-TOKEN>' \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' -d '
{
  "user_id": "<SOME-USER-ID>",
  "phone": "12345678",
  "unsubscribed_from_emails": false
}'
```

snippet code Javascript
```js
import Intercom from 'react-native-intercom';

Intercom.updateUser({
  phone: '12345678',
  unsubscribed_from_emails: false,
});
```
PS: the phone field's updated

**Comment by onlydave** [comment]
The issue may be resolved by updating to `^5.0.2` of the [intercom-ios](https://github.com/intercom/intercom-ios/blob/760119ac0a2c44512094dc972857abe521b249b7/CHANGELOG.md#502-2018-05-02) framework and then changing [IntercomUserAttributesBuilder.m:35](https://github.com/tinycreative/react-native-intercom/blob/master/iOS/IntercomUserAttributesBuilder.m#L35) to:
```
attributes.unsubscribedFromEmails = [[attributesDict objectForKey:@"unsubscribed_from_emails"] boolValue];
```

`attributes.unsubscribedFromEmails` needs to be a straight up bool, not NSCFBoolean. (Know very little about objective C, mostly trial and error)

**Comment by Br1an-Boyle** [comment]
I pushed an update to fix this in release 5.0.2 today 😉

**Comment by onlydave** [comment]
Hi @bboyle18 

This package would still need to be updated to send unsubscribedFromEmails as a boolean?

At the moment I think it ends up as a String [IntercomUserAttributesBuilder.m:35](https://github.com/tinycreative/react-native-intercom/blob/master/iOS/IntercomUserAttributesBuilder.m#L35) 
```
    if ([self stringValueForKey:@"unsubscribed_from_emails" inDictionary:attributesDict]) {
        attributes.unsubscribedFromEmails = [self stringValueForKey:@"unsubscribed_from_emails" inDictionary:attributesDict];
    }
```

```
+ (NSString *)stringValueForKey:(NSString *)key inDictionary:(NSDictionary *)dictionary {
    NSString *value = dictionary[key];
    if ([value isKindOfClass:[NSString class]]) {
        return value;
    }
    if ([value isKindOfClass:[NSNumber class]]) {
        return [NSString stringWithFormat:@"%@", value];
    }
    if ([value isKindOfClass:[NSNull class]]) {
        return [ICMUserAttributes nullStringAttribute];
    }
    return nil;
}
```

**Comment by onlydave** [comment]
After updating to 11.0.0 and updating the framework to the latest from https://github.com/intercom/intercom-ios I'm just getting the following error. Tried unlinking and cleaning and re-adding everything every way I can think of it but it still can't seem to find the Intercom header

`OURAPP/node_modules/react-native-intercom/iOS/IntercomUserAttributesBuilder.m:10:9: 'Intercom/Intercom.h' file not found`

Anyone have any ideas?
